version: "3.9"
services:
  apiService:
    image: "truelistingapi"
    # container_name: "truelistingapi"
    environment:
      - host=truelistingDB
      - apiHost = localhost
      - apiPort = 3090
    deploy:
      replicas: 2
  
      